language: c
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libunwind8
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - secure: "LK5FHdPiguTxnhEpOHIabuO7CBYCwCH6liJad+6NooqbTYfhFfwArAVWRS6MsJ4JXMZEI6JTHH9z9be/U1c2TplHUBuWubNIHSioE2jp1fsdXFMMxk1BZSSe9uaT2hSrS+8QKnWHazVISBsbYakgsiKrhY7dlhkKdjBCqR+hQdNwnZVTs8hVUZxASye59aM8LMtonnYhqSjq3Wbt3hmBs+tqTQRpUH1m5uiWeXg1HE0Ccv+TMXPUdiLUEGquNx1FHaS2Kskl8ij5Ya50v/ujD8SgxbAFaf66nnk8InVDfA+XKsu5t4IayprY0yw0FvKJ9DzDNoNLbWFJv3Ak2J002CF+5L+GSZt/j1mPEfU7sBkxORplyi7NreFcSwcK8xSxsJkbDa6kNNAL3APHn1QzVaOh5JKOFWfkz5V/USWDiBCPzTA1Ly9O5JjCR9gla+t827Hj63lcDE3c05wD4NTchoyKi2Fdtf8XY4QcsAuonKCmFSBf2U0utG181g1JcVA1/lN+hM7tKrk0m/ZbTmZ8XkqH0+K/0k3ezhQNLZ13Q2lYmHXmU9+ONyFMAdKJ+BSCe/2bkFh5+c9sXrFp0GPzWvnP9FerMkbNqx68hdtUoflUaYfrG9XVI6mFH+H+YE17Jysc70U1FATRaKOLiu0KLrmsj2pxdghWg4fR0rbRjyU="

before_install:
- wget https://download.visualstudio.microsoft.com/download/pr/c624c5d6-0e9c-4dd9-9506-6b197ef44dc8/ad61b332f3abcc7dec3a49434e4766e1/dotnet-sdk-3.0.100-preview7-012821-linux-x64.tar.gz -O dotnet-sdk-latest-linux-x64.tar.gz
- sudo mkdir /opt/dotnet
- sudo tar xvf dotnet-sdk-latest-linux-x64.tar.gz -C /opt/dotnet
- sudo ln -s /opt/dotnet/dotnet /usr/bin/dotnet
script:
- pushd samples/KestrelSample && dotnet restore && dotnet build && popd
- pushd test/RedHat.AspNetCore.Server.Kestrel.Transport.Linux.Test && dotnet restore && dotnet test && popd
- dotnet pack src/RedHat.AspNetCore.Server.Kestrel.Transport.Linux --configuration Release --version-suffix "$(date +"%y%m%d")-$TRAVIS_BUILD_NUMBER"
  --output .
after_success:
- 'if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  curl -H "X-NuGet-ApiKey: $NUGET_APIKEY" -T RedHat.AspNetCore.Server.Kestrel.Transport.Linux.*.nupkg
  https://www.myget.org/F/redhat-dotnet/api/v2/package ; fi'
